version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.6.20-full  # Hỗ trợ Python 3.10
    ports:
      - "5005:5005"  # REST và SocketIO endpoint
    volumes:
      - /home/hoangphuc/Documents/ciesta-asisstant:/ciesta-asisstant  # Mount giống Dev Container
    command: run -m models --enable-api --cors "*" --debug  # Enable API cho channels
    user: root  # Đồng bộ với remoteUser: root
    environment:
      - ACTION_SERVER_URL=http://action_server:5055/webhook
      - SOCKETIO_URL=http://localhost:5005
      - RASA_ENTERPRISE_URL=http://localhost:5002/api
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - action_server
      - redis
    network_mode: host  # Đồng bộ với runArgs: "--network=host"
    run_args:  # Đồng bộ với runArgs trong Dev Container
      - "--env=DISPLAY"
      - "--env=WAYLAND_DISPLAY"
      - "--env=XDG_RUNTIME_DIR=/run/user/1000"
      - "--volume=/run/user/1000:/run/user/1000"
      - "--device=/dev/dri"
      - "--mount=type=tmpfs,target=/tmp"

  action_server:
    image: rasa/rasa-sdk:3.6.2
    ports:
      - "5055:5055"
    volumes:
      - /home/hoangphuc/Documents/ciesta-asisstant/actions:/app/actions
    command: start --actions actions --debug
    user: root
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    user: root
    network_mode: host